### ISSUE TITLE
If there are no notes for a recurring entry, load will fail.

### ISSUE THREAD

**Issue by Artemis-Hunt** [AY2021S1-CS2113-T16-1/tp#127]
![image](https://user-images.githubusercontent.com/62279011/97586575-61b87700-1a35-11eb-89e6-70d348455be9.png)
If there are no notes entered (since it is an optional param) classContents[6] will not exist, since there will be nothing in index 7 after split(";") and there will be ArrayOutOfBounds exception.

**Comment by Feudalord** [comment]
fixed
