### ISSUE TITLE
Too detailed class diagrams

### ISSUE THREAD

**Issue by yueyeah** [AY2021S1-CS2113-T16-1/tp#210]
<img width="542" alt="T16-1-1" src="https://user-images.githubusercontent.com/40558118/97783557-95310800-1bd3-11eb-9cdb-a4018c2d4da5.png">

Too much detail. You may want to consider leaving out some or even all the methods as based on your explanation, the diagram just needs to show how the classes are related to each other. This goes for your other class diagrams as well: tailor the detail of your diagrams to the corresponding description.

**Comment by kaiwen98** [comment]
Noted with thanks.
