### ISSUE TITLE
Minor correction for Ledger Creation Sequence Diagram 

### ISSUE THREAD

**Issue by yueyeah** [AY2021S1-CS2113-T16-1/tp#211]
<img width="636" alt="T16-1-2" src="https://user-images.githubusercontent.com/40558118/97783584-c7db0080-1bd3-11eb-9e08-ef6d026e5dec.png">

It may be better to remove the : before `ledger:Ledger`. 
Also, is `Entry()` the constructor for `Ledger`?

Nice usage of lines to demarcate the control flow!

**Comment by kaiwen98** [comment]
Noted with thanks.
