### ISSUE TITLE
If gt.load() fails to load then mt.load() and at.load() is not executed

### ISSUE THREAD

**Issue by Artemis-Hunt** [AY2021S1-CS2113-T16-1/tp#87]
If an exception is thrown during any one of the loads, the loads that come after it is not executed due to try...catch. Each load function should be in it's own try-catch block, and the error message (if any) should be made more prominent and specific (e.g. Loading of goals failed!) instead of "An exception has occurred"

**Comment by Feudalord** [comment]
Settled. Seperated exception handling and more detailed error message.
